spring:
  datasource:
    url: ${DB_ADDR:jdbc:mariadb://admin-db:3306/jpa}
    username: ${DB_USERNAME:grooo-sample}
    password: ${DB_PASSWORD:grooo~!}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  messages:
    basename: i18n/messages,i18n/args
    cache-duration: 3600
    encoding: UTF-8
  web:
    locale: ja
logging.level:
    org.hibernate:
      type: trace
      SQL: ${DB_LOGLEVEL:DEBUG}
jwt:
  secret: my-super-secret-key-that-is-long-enough-123456
  expiration: 3600000
